version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=EXTERNAL://:29092,INTERNAL://127.0.0.1:9092
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://:29092,INTERNAL://127.0.0.1:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=EXTERNAL
    depends_on:
      - zookeeper

  consumer:
    image: ghcr.io/i-sevostyanov/k8s-playground:consumer-v0.1.0
    ports:
      - 8080:8080
    environment:
      - KAFKA_ADDR=kafka:29092
      - INPUT_TOPIC=input
      - OUTPUT_TOPIC=output
      - LISTEN=localhost:8080
    depends_on:
      - kafka

  producer:
    image: ghcr.io/i-sevostyanov/k8s-playground:producer-v0.1.0
    ports:
      - 8081:8080
    environment:
      - KAFKA_ADDR=kafka:29092
      - TOPIC=input
      - LISTEN=localhost:8081
    depends_on:
      - kafka
