IMAGE_NAME = "bento/ubuntu-18.04"
N = 2
VERSION = "0.1.0"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "master"
        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "provision/k8s-master.yml"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "k8s-node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible_local" do |ansible|
                ansible.playbook = "provision/k8s-node.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
            end
        end
    end

    config.vm.define "management" do |management|
        management.vm.box = IMAGE_NAME
        management.vm.network "private_network", ip: "192.168.50.13"
        management.vm.hostname = "management"
        management.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "provision/management.yml"
            ansible.extra_vars = {
                node_ip: "192.168.50.13",
                version: VERSION,
            }
        end
    end
end
