apiVersion: v1
kind: Service
metadata:
  name: "kafka-exporter"
  namespace: default
  labels:
    app: "kafka-exporter"
spec:
  type: ClusterIP
  ports:
    - port: 9308
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: "kafka-exporter"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "kafka-exporter"
  labels:
    app: "kafka-exporter"
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: "kafka-exporter"
  endpoints:
    - port: metrics
      interval: "30s"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kafka-exporter"
  labels:
    app: "kafka-exporter"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kafka-exporter"
  template:
    metadata:
      labels:
        app: "kafka-exporter"
    spec:
      containers:
        - name: kafka-exporter
          image: "danielqsj/kafka-exporter"
          imagePullPolicy: IfNotPresent
          args:
              - "--kafka.server=kafka.default.svc.cluster.local:9092"
          ports:
            - name: metrics
              containerPort: 9308
              protocol: TCP
