apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
    - name: listener
      port: 2181
    - name: zookeeper-2888
      port: 2888
    - name: zookeeper-3888
      port: 3888
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.6.2
          ports:
            - name: listener
              containerPort: 2181
            - name: zookeeper-2888
              containerPort: 2888
            - name: zookeeper-3888
              containerPort: 3888
          env:
            - name: ZOO_PORT
              value: "2181"
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_SERVERS
              value: "server.1=0.0.0.0:2888:3888;2181 "
            - name: ZOO_INIT_LIMIT
              value: "3"
            - name: ZOO_SYNC_LIMIT
              value: "2"
            - name: ZOO_AUTOPURGE_PURGEINTERVAL
              value: "1"
            - name: ZOO_AUTOPURGE_SNAPRETAINCOUNT
              value: "10"
